### ISSUE TITLE
Cubie Board

### ISSUE THREAD

**Issue by M-Razavi** [ccrisan/thingos#12]
Would it be possible to add support for Cubie Board?

**Comment by ccrisan** [comment]
Cubie Boards have been, in my opinion, unnecessarily large and too expensive for what they have to offer. That's why I prefer concentrating on other more accessible boards. Do you have a specific board model in mind?

**Comment by M-Razavi** [comment]
Cubie Board 2 has reasonable price and performance. I use it for many of my projects. I think you should change your mind:)

**Comment by ccrisan** [comment]
I still consider it expensive for what it has to offer (~$64 on ebay) but if you really want me to port thingOS to Cubie Board 2, you can send me one board and I'll see what I can do. See [this motionEyeOS FAQ entry](https://github.com/ccrisan/motioneyeos/wiki/FAQ#can-motioneyeos-be-ported-to-insert-your-board-here).
