### ISSUE TITLE
No network created

### ISSUE THREAD

**Issue by AlexTollola** [ccrisan/thingos#16]
Hi, I´ve already included the dnsmasq.conf and the hostapd.conf files in the boot partition. I also modified the os_networkless configuration and set it to true. But after initializing my raspberry it won´t create the network.

**Comment by ccrisan** [comment]
@AlexTollola have you solved the issue? Or did you close it by accident?

**Comment by AlexTollola** [comment]
Hi, no I created the issue in the wrong section, but I still have the
problem.
I am working in Motioneye OS, and I need it to be configured as a WiFi
Acces Point.
I follow all the instructions but i can't make it work. The netowork wont
appear.
I appreciate if you could help me with this Issue.
Thank you for tour attention.


El 15/11/2018 9:49 a. m., "Calin Crisan" <notifications@github.com>
escribió:

@AlexTollola <https://github.com/AlexTollola> have you solved the issue? Or
did you close it by accident?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ccrisan/thingos/issues/16#issuecomment-439087405>, or mute
the thread
