### ISSUE TITLE
Bug; missing brcmfmac43455-sdio.clm_blob for Raspberry PI 3

### ISSUE THREAD

**Issue by klaus-ditze** [ccrisan/thingos#31]
`brcmfmac43455-sdio.clm_blob` file from `https://github.com/RPi-Distro/firmware-nonfree/raw/master/` must be in `thingos/tree/dev/board/raspberrypi3/overlay/lib/firmware/brcm`

see https://github.com/ccrisan/motioneyeos/issues/2090

**Comment by ccrisan** [comment]
Fixed via 96a19ddb3143e34b1c46001371fea002331c9356. Thanks for reporting this issue.
