### ISSUE TITLE
GCC 5.x compiler

### ISSUE THREAD

**Issue by cedricve** [ccrisan/thingos#40]
Hey @ccrisan 

A long time ago, hope you are still doing great. I'm trying out your latest version of thingos, but noticed it will install GCC 8.2.1 when BR2_TOOLCHAIN_EXTERNAL=y

Any idea how I can force the system to install a 5.x compiler?

Many thanks!

**Comment by ccrisan** [comment]
@cedricve you should be able to choose a custom toolchain and specify its URL. You'll just need to find a toolchain that suits your needs.

**Comment by cedricve** [comment]
Thanks @ccrisan, I was looking around and saw here you declare some version for gcc https://github.com/ccrisan/thingos/blob/dev/configs/raspberrypi_defconfig#L11.

II thought to try this out but still installs GCC 8.2.1. Is this expected behaviour?

**Comment by ccrisan** [comment]
@cedricve are you sure it installs GCC 8.x? It should install the toolchain found at given URL (in this particular example it's https://github.com/raspberrypi/tools/archive/5caa7046982f0539cf5380f94da04b31129ed521.tar.gz). And that's a GCC 4.9 toolchain as far as I can see.

**Comment by cedricve** [comment]
That's indeed what I was expecting. I just confirm it downloads the 4.9.3 version when compiling the raspberrypi version. However when copying this part (https://github.com/ccrisan/thingos/blob/dev/configs/raspberrypi_defconfig#L6-L14) to raspberrypi3, it downloads toolchain-external-arm-arm 2018.11

**Comment by ccrisan** [comment]
Raspberry PI3 should use https://github.com/ccrisan/thingos/blob/dev/configs/raspberrypi3_defconfig and works well with GCC 8.x.

You shouldn't copy toolchain-related stuff from Raspberry Pi (1st gen models) to Raspberry Pi 3, as they are quite different in this way.

**Comment by cedricve** [comment]
Yeah, makes sense, however I'm trying out a c program that requires a version GCC 4.x. That's why I'm trying to change the GCC version.

**Comment by ccrisan** [comment]
@cedricve ah, ok. Then make sure you remove the `output/raspberrypi3/.config` file after updating the `configs/raspberrypi3_defconfig` and before building. Also, do a `./build.sh raspberrypi3 xconfig` and browse through the UI to make sure the changes are indeed taken into consideration. Otherwise, it should work.

**Comment by cedricve** [comment]
Thanks @ccrisan, by now I dived a little bit deeper, and trying other toolchains as suggested. However have some issues with the check linux-headers (which are not equal).

    xzcat /root/motioneyeos/dl/toolchain-external-arm-arm/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux.tar.xz | tar --strip-components=1 -C     /root/motioneyeos/output/raspberrypi3/build/toolchain-external-arm-arm-2014.09 --        exclude='usr/lib/locale/*'   -xf -
    rm -rf /root/motioneyeos/output/raspberrypi3/host/opt/ext-toolchain
    mkdir -p /root/motioneyeos/output/raspberrypi3/host/opt/ext-toolchain
    mv /root/motioneyeos/output/raspberrypi3/build/toolchain-external-arm-arm-2014.09/*     /root/motioneyeos/output/raspberrypi3/host/opt/ext-toolchain/
    >>> toolchain-external-arm-arm 2014.09 Patching
    >>> toolchain-external-arm-arm 2014.09 Configuring
    Incorrect selection of kernel headers: expected 4.20.x, got 3.1.x

**Comment by ccrisan** [comment]
You'll need to specify the correct kernel headers version in your buildroot configuration, according to the message.

**Comment by cedricve** [comment]
Yeah tried a couple of things already (setting custom LINUX-headers), can you give any direction? Thanks for the help @ccrisan.

**Comment by cedricve** [comment]
hmm looks I cannot select it anymore.

<img width="508" alt="Screenshot 2019-11-28 at 10 50 39" src="https://user-images.githubusercontent.com/1546779/69795704-efa83400-11cc-11ea-9493-bd40460e4e23.png">

**Comment by ccrisan** [comment]
Then, if you must use GCC 4.x, you'll probably have to use an old version of Buildroot (and thus thingOS). I'd recommend though that you concentrate your effort into compiling your software on a more recent GCC.

**Comment by cedricve** [comment]
Got it working by defining an old toolchain + patches to the existing C project. Thanks for helping!
