### ISSUE TITLE
Upgrade script

### ISSUE THREAD

**Issue by cedricve** [ccrisan/thingos#42]
Hey Crissan,

Maybe I didn't looked deep enough, but I remember that the upgrade procedure changed over time? Can you tell me where I can find it?

Cédric

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/thingos/wiki/Firmware-Updates. It should be up to date. If you find anything that's changed or mismatching, please let me know.

**Comment by cedricve** [comment]
gotcha, so basically calling your fwupdate shell script could do the job.

**Comment by ccrisan** [comment]
I wouldn't see it any other way :)

**Comment by cedricve** [comment]
In the past I executed the different steps from a script using system calls. Thanks for feedback.
