### ISSUE TITLE
Wiki: Building OS Images is missing

### ISSUE THREAD

**Issue by cedricve** [ccrisan/thingos#43]
no content is available under the wiki page: Building OS Images

**Comment by ccrisan** [comment]
No time is available to write the other half of the missing but listed wiki pages :)

**Comment by cedricve** [comment]
Will document that page very soon. Should I post it here? @ccrisan

**Comment by ccrisan** [comment]
Honestly, i have no idea what's the best way to collaborately manage a GitHub wiki. Posting it here surely is one option that we can use, for now.

**Comment by ccrisan** [comment]
Lots of wiki pages are missing and have been planned but I had no time to write content for them. I'm accepting user-contributed content though :)
