### ISSUE TITLE
sshd fails to start

### ISSUE THREAD

**Issue by dzianisv** [ccrisan/thingos#50]
I have build a bananapim1 image
```
git clone <repo> --branch master --depth 1
cd thingos
./build.sh bananapim1
./build.sh bananapim1 mkrelease 
sudo ./writeimage.sh -d /dev/sdb -i output/bananapim1/images/thingos-bananapim1.img
```
SSH starts to work soon after first boot, but stops to work after reboot and next boots.

[log.zip](https://github.com/ccrisan/thingos/files/4174161/log.zip)

**Comment by ccrisan** [comment]
@denis4net please try latest `dev` branch. It contains a large amount of changes, including SSH. Make sure you're doing a clean build.

**Comment by denis4net** [comment]
With dev, I had another issue. init.d script doesn't start at all and I don't know why. The OS is loaded, the host is reachable through ICMP ECHO (ping). So, I haven't had time to do debugging and switched to armbian :(. I will try later on another board.

**Comment by ccrisan** [comment]
> With dev, I had another issue. init.d script doesn't start at all and I don't know why.

Could you please post your boot log? Solving SSH issues is kind of critical.

**Comment by ccrisan** [comment]
Closing due to lack of feedback.
