### ISSUE TITLE
Just changing version does not change the rootfs

### ISSUE THREAD

**Issue by avanc** [ccrisan/thingos#59]
I changed board/common/overlay/etc/version and did
    ./build.sh raspberrypi
    ./build.sh raspberrypi mkrelease

A corresponding image file is created. However, the rootfs is not updated (/etc/version still has the old content).

This lead to some confusion.

**Comment by avanc** [comment]
As a side note: I changed neon to support TLS/SSL and did a rebuild. But it seems that this didn't trigger a kernel rebuild. Do I have e misunderstanding of the buildroot capabilities?

**Comment by avanc** [comment]
I have to add: the new image is identical (md5sum) to the first build!
However, the root.tar file does contain the changed version file.
So it seems that the image is wrongly created...
Any hints would be really appreciated.

**Comment by ccrisan** [comment]
Normally, BuildRoot recommends a clean build with every possible change. I know it's painful to wait for a full build which takes forever, so if you just want to rebuild your system including the changes, you can do:

    ./build.sh raspberrypi  # will (re)build new packages
    ./build.sh raspberrypi mkimage  # will create the actual OS image, uncompressed
    ./build.sh raspberrypi mkrelease  # will compress the image and prepare the final, properly named archive

Keep in mind that if you changed an option to a certain package, you'll probably need to explicitly rebuild that package, using `./builld.sh raspberrypi ${package}-dirclean` followed by `${package}-rebuild`.

Also, the mkrelease is optional and doesn't really help during development, since you're probably looking for an uncompressed image to write to the SD card, which is prepared by `mkimage`.

I hope this helps.

**Comment by avanc** [comment]
Thanks for the hint.
For rebuild, is

    make clean all

enough? Or should it be

    make clean world

**Comment by ccrisan** [comment]
You can simply run `./build.sh raspberrypi clean` (`build.sh` is, in many cases, just a proxy command for `make`).

In any case, everything that's being built resides in the `output/raspberrypi` folder. You can simply remove it and your build system will rebuild everything from scratch. Keep in mind though that your configuration, unless explicitly saved with `./build.sh raspberrypi savedefconfig`, resides in `output/raspberrypi` as well and will be lost.

**Comment by avanc** [comment]
OK, that helps.

For completeness: To rebuild kernel i found

./build.sh raspberrypi linux-dirclean
./build.sh raspberrypi linux-rebuild

It's really a pitty that buildroot does not detect changes, although it heavily depends on Makefiles.

**Comment by ccrisan** [comment]
Yes, you are right: the kernel is seen as a package, so the package rebuild remark applies.

**Comment by avanc** [comment]
Thanks for quick help. I got it successfully build.

**Comment by avanc** [comment]
@ccrisan Sorry for using this closed issue, but you mentioned:
> Also, the mkrelease is optional and doesn't really help during development, since you're probably looking for an uncompressed image to write to the SD card, which is prepared by `mkimage`.

But fwupdate upgrade does not accept an image file. I tried to copy the file to /data/.fwupdate/firmware.img but flashing is still not possible. How to feed the image into a running system?

**Comment by ccrisan** [comment]
@avanc are you sure the `fwupdate` won't accept an image file? Support for such a feature has been added more than a year ago. What does it say? Do you get an error?

P.S. you may need to specify the path to an archived (.xz or .gz) image rather than an uncompressed one.

**Comment by avanc** [comment]
Ah, I thought I can use fwupdate also with an uncompressed image to speed up development (i.e. not compressing on host and not decompressing on target).
