### ISSUE TITLE
Adding a new Board (x86_64)

### ISSUE THREAD

**Issue by zeridon** [ccrisan/thingos#61]
I find myself in need to do a x86_64 board (well actually a PC) and find that it is currently possible. How to approach adding a new board.

BR

**Comment by ccrisan** [comment]
I have a few problems with x86/x64 platforms and thingOS:

 1. The "PC" is not really a SBC and I personally wouldn't know how to build an OS image that would simply boot on any x86/x64 machine.
 2. thingOS is meant to be run on SBCs, effectively transforming them into devices whose firmware can be easily managed (customized at build time, upgradable over-the-air and not tampered with at runtime); PCs don't really fall into this category
 3. thingOS has to be small; PCs inherently have a large number of possible peripherals thus they need all kinds of drivers that a linux Kernel can provide

This being said, I'm not against adding support for a particular x86/x64 SBC but to say that we want an OS image for PC is like saying that we want an OS image for "ARM". One size does not fit all.

Please correct me if I'm wrong or if I'm missing something.

**Comment by zeridon** [comment]
Frankly said, SBC is not so different from PC. Yes indeed it is inherently more expandable and uncontrollable in terms of what is inside and what can be added.

My speciffic case is x86_64 poslike device (single hardware config). Speciffic drivers/tooling is not a point of discussion. All the hw there is in the device itself is fully supported in standard kernel. On the other hand i would very much like to get the benefit of "devices whose firmware can be easily managed" with all the ramifications present in that statement.

E.g. if we simplify this to let's say Intel NUC (which seems to be quite the standard in some projects dealing with IoT) with pretty much predefined hw, that is fine by me.

To make myself more clear (as it seems i missed that) i am not asking for commiting to support a generic x86 board (with all possible problems) just inquiring how to approach the task of adding speciffic x86 board (e.g. virtualbox/qemy-x86/kvm/NUC). Probably initial target would be best to be some virtualization platform as there the hardware is quite fixed and mostly SBClike treatable.

The wiki topic https://github.com/ccrisan/thingos/wiki/Add-New-Board seems a good start but somehow feels lacking, nevertheless i will do my best to follow along and see what happens.

BR

**Comment by ccrisan** [comment]
X86(_64) is not a board but rather an architecture. We might eventually add support for a particular board which uses an X86_64 CPU, but we can't generally support "X86_64" systems under a single board type.
