### ISSUE TITLE
Wrong FAT in wiki/Partitions

### ISSUE THREAD

**Issue by PsyEng** [ccrisan/thingos#62]
The Wiki mentions the boot partition as FAT32, but it was never FAT32, instead, it´s FAT16.
https://github.com/ccrisan/thingos/blob/38f584720725866acc251d24d821e34362bec665/board/common/mkimage.sh#L46

**Comment by ccrisan** [comment]
That is correct. For small partitions (below a couple hundreds of MB IIRC) the recommended FAT variant is 16. I now updated the Wiki page to simply say "FAT".

Thanks!
