### ISSUE TITLE
Need to update wpa_supplicant.con info

### ISSUE THREAD

**Issue by starbasessd** [ccrisan/thingos#65]
https://github.com/ccrisan/thingos/wiki/wpa_supplicant.conf
Need to add country code as:
country=US # Use appropriate country code

**Comment by ccrisan** [comment]
The example is provided as a minimal example. We don't intend to provide full configuration files for the various components thingOS offers.

**Comment by starbasessd** [comment]
Unfortunately, it is an example that is broken. Without at least the country code, the rest of the wifi process will shut down wifi.

**Comment by ccrisan** [comment]
That's strange! I've been using configs that have only the following content without any problem:

    network={
        ssid="my_ssid"
        psk="my_psk1234"
    }
