### ISSUE TITLE
Wiki: no space usage estimation in Getting Started's Prerequisites

### ISSUE THREAD

**Issue by d-faure** [ccrisan/thingos#66]
I know the thing is rather minor, but it would be comfortable to provide an estimation of the disk space usage for a complete build which could become quite large with the firmware downloads.

Noticeably, I found that building a simple Raspberry Pi (v1) dedicated install is requiring around 9.3 Gb, with 6.3 Gb for the target system build and created image themselves.

**Comment by ccrisan** [comment]
The required storage space depends on the final OS and its uses. There's no way we can estimate what a minimum value would be for each particular OS build and there's no point in indicating a bare minimum of a few tens of hundreds of MB just to have a number.
