### ISSUE TITLE
Several missing Wiki pages

### ISSUE THREAD

**Issue by starbasessd** [ccrisan/thingos#67]
Marked in red in Right column:
Batteries Included, Network Connections
Core Features
     Reliability, Other Goodies
Internals
     Boot Process
Source Code
     Board Configurations
     Building OS Images
     Add New Packages
FAQ
Troubleshooting
Various
     Add a RTC Module

All Red Links point back to Home Wiki page.

**Comment by ccrisan** [comment]
Yes, those wiki pages are currently missing and are basically part of a wider documentation plan. They will hopefully be written one day. Until then, let's keep them there so we don't forget about them.
