### ISSUE TITLE
Building on Arch Linux host broken

### ISSUE THREAD

**Issue by avanc** [ccrisan/thingos#69]
Due to an incompatibility between glibc 2.33 and fakeroot, the system cannot be build on e.g. [Arch Linux](https://bugs.archlinux.org/task/69572). There is a patch for fakeroot in buildroot: https://git.busybox.net/buildroot/commit/?id=f45925a951318e9e53bead80b363e004301adc6f

As I want to avoid doing cherry-picking and going out of sync with thingOS, it would be great if you can upgrade the underlying buildroot.

**Comment by ccrisan** [comment]
The plan is to have a branch that corresponds to a new version of BuildRoot some time in the near future, as per https://github.com/ccrisan/thingos/wiki/Branches. In the meantime I cherry-picked the commit you indicated into our `dev` branch. Let me know if it works for you now.

**Comment by avanc** [comment]
Thanks. It compiles again without problems.
