### ISSUE TITLE
why does motioneyeos always fail on boot at wpa_supplicant?

### ISSUE THREAD

**Issue by imperialdalek** [ccrisan/thingos#73]
I have both Pi Zero W and Pi Zero.
I've tried 20190911 and 20200606 versions of moionEyeOS for raspberry-pi and they both fail at the wpa_supplicant.conf stage.

What's the issue? 

It may also be useful to highlight the link from MotionEye wiki now goes to a different product's page for `wpa_supplicant.conf ` and the example code snippet isn't the same as the one you can find (if you look hard enough) on motioneye wiki.
In brief, the example on "thingos" is missing both "country" and "scan_ssid" params.

For the avoidance of doubt, I followed the instructions to the letter changing the line endings to unix, (this isn't my first Pi rodeo)
I also installed Notepad++ as per recommendation to see if it made a difference - it didn't.
The same wpa_supplicant error was displayed for both versions, using fresh install each time.
None of the install attempts passed the wpa_supplicant step in the init process, 
causing a kernel panic due to network and exit from boot process.

What am I doing wrong?
Suggestions gratefully received.

**Comment by starbasessd** [comment]
There isn't ANY networking available natively in the RPiZero (V1.3), and you should put in a os.conf file with [OS_NETWORKLESS=true](https://github.com/ccrisan/thingos/wiki/os.conf#os_networkless) unlike PiZeroW or PiZero2W which have wireless built in. You could add a USB dongle for wifi or ethernet to the PiZero V1.3 and it would work normally.

**Comment by ccrisan** [comment]
Branch https://github.com/ccrisan/thingos/tree/version-2021.11 (soon to be merged) will add support for RPi Zero 2W.

**Comment by ccrisan** [comment]
Branch `version-2021.11` has been merged into `dev`.
