### ISSUE TITLE
Support for Raspberry Pi Zero 2 W

### ISSUE THREAD

**Issue by avanc** [ccrisan/thingos#75]
I created this issue to keep track of the current status of supporting the new Raspberry Pi Zero 2 W.

I exists already a [patch for buildroot](https://lists.buildroot.org/pipermail/buildroot/2021-October/627044.html). However, it is not integrated into buildroot yet.

**Comment by avanc** [comment]
I applied the patch https://github.com/ccrisan/motioneyeos/pull/2829 from @jawsper to [my thingOS based project](https://github.com/avanc/photOS/commits/zero2) without conflicts. It works like a charm.

**Comment by ccrisan** [comment]
The plan is to merge in the latest BuildRoot release and, if needed, separately update all Raspberry Pi-related packages. However that's a more tedious procedure than a simple `git merge`. I'll take care of it however in the near future.

In the meantime, applying a patch as you did is indeed the perfect immediate solution.

**Comment by marsmaennchen** [comment]
When i download the from https://github.com/jawsper/motioneyeos/releases/tag/20211113 wich should work with pi zero2.
But the wpa_supplicant file won´t work.
At startup i got the message " no device found" Any idea what i did wrong?

**Comment by thicla01** [comment]
@marsmaennchen look at https://github.com/jawsper/motioneyeos/releases/tag/20220119-dev

**Comment by ccrisan** [comment]
Current `dev` branch has support for Raspberry Pi Zero 2W.
