### ISSUE TITLE
Missing directories after firmware upgrade

### ISSUE THREAD

**Issue by jasaw** [ccrisan/thingos#8]
Directory structure in /data is only copied from dataskel if it has just created the data partition. If doing firmware upgrade, new contents in dataskel are not copied to existing data partition.
Example:
varlib was added recently, so upgrading from old firmware will cause /var/lib symlink to break.

**Comment by ccrisan** [comment]
The `/data` folder is _created_ from the provided skeleton but never _updated_ from the skeleton. If you need to modify its contents with a firmware update, please use [Post-upgrade Scripts](https://github.com/ccrisan/thingos/wiki/Firmware-Updates#post-upgrade-scripts).
