### ISSUE TITLE
FTP WebCam

### ISSUE THREAD

**Issue by DL7AG-Berlin** [ccrisan/thingos#83]
With a normal WebCam, only one image is needed at a time, the current one on the FTP server.
With a recording for example of every 5 minutes a picture.
This means that the older image is overwritten with the new one.
But what are the settings for this?
Every 5 minutes a picture, upload always with the same name on the FTP server.
...Chris

**Comment by ccrisan** [comment]
Wrong repo. Here's what you're looking for: https://github.com/motioneye-project/motioneyeos.
